 version: 2
 jobs:
   build:
     docker:
       - image: circleci/php:7.1-apache
     steps:
       - checkout
       - run:
           name: Copy project directory to default apache root
           command: sudo cp -R ~/project /var/www/html/
       - run: 
           name: Start apache
           command: sudo /init.d/apache2 start
      
