version: 2.1

orbs:
  trakr: trakrtest/web-test@dev:0.0.2

executors:
  lamp:
    docker:
      - image: circleci/php:7.1-apache

jobs:
  build:
     executor: lamp
     environment:
       TUNNEL_PORT: 80
     steps:
       - checkout
       - run:
           name: Copy project directory to default apache root
           command: sudo cp -r ~/project/* /var/www/html/
       - run:
           name: Start apache
           command: sudo /etc/init.d/apache2 start
       - run:
           name: Install localtunnel
           command: sudo apt-get update
       - run: sudo apt-get install curl software-properties-common
       - run: curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -
       - run: sudo apt-get install nodejs
       - run: sudo npm install -g localtunnel
       - run:
           name: Clone test integration
           command: sudo git clone https://github.com/makehero/trakr_circleci.git $HOME/trakr_circleci
       - run: cd $HOME/trakr_circleci && sudo npm install
       - run:
           name: Start tunnel
           command: sh $HOME/trakr_circleci/start_tunnel.sh
           background: true
       - run:
          name: Check test status
          command: node $HOME/trakr_circleci/wait_for_test.js
  test:
     executor: trakr/default
     steps:
       - trakr/fetch_test
       - trakr/trigger_test:
           trakr_base_env: production
           delay_start: 30 # Delay the start for testing by 30 seconds 

workflows:
  build-tunnel-test:
    jobs:
      - build
      - test
