version: 2.1

orbs:
  trakr: trakrtest/web-test@dev:0.0.1

executors:
  lamp:
    docker:
      - image: circleci/php:7.1-apache

jobs:
  build:
     executor: lamp
     environment:
       TRAKR_BASE_ENV: production
     steps:
       - checkout
       - run:
           name: Copy project directory to default apache root
           command: sudo cp -R ~/project /var/www/html/
       - run:
           name: Start apache
           command: sudo /etc/init.d/apache2 start
  tunnel:
      executor: lamp
      steps:
       - run:
           name: Install localtunnel
           command: sudo apt-get update
       - run: sudo apt-get install curl software-properties-common
       - run: curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -
       - run: sudo apt-get install nodejs
       - run: sudo npm install -g localtunnel
       - run:
           name: Clone test integration
           command: sudo git clone https://github.com/makehero/trakr_circleci.git $HOME/trakr_circleci
       - run: cd $HOME/trakr_circleci && sudo npm install
       - run:
           name: Start tunnel
           command: sh $HOME/trakr_circleci/start_tunnel.sh
           #background: true

workflows:
  build-tunnel-test:
    jobs:
      - build
      - tunnel:
          requires:
            - build
      - trakr/trakr_test:
          requires:
            - build
