version: 2
jobs:
  build:
     docker:
       - image: circleci/php:7.1-apache
     environment:
       TRAKR_BASE_ENV: production
       TUNNEL_PORT: 80
     steps:
       - checkout
       - run: sudo cp -r ~/project/* /var/www/html/
       - run: sudo /etc/init.d/apache2 start
       - run: sudo apt-get update
       - run: sudo apt-get install curl software-properties-common
       - run: curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -
       - run: sudo apt-get install nodejs
       - run: sudo npm install -g localtunnel
       - run: sudo git clone https://github.com/makehero/trakr_circleci.git $HOME/trakr_circleci
       - run: cd $HOME/trakr_circleci && sudo npm install
       - run:
           name: Start tunnel
           command: sh $HOME/trakr_circleci/start_tunnel.sh
           background: true
       - run:
          name: Perform test
          command: BUILD_URL=https://trakr-project-$TRAKR_PROJECT_ID.localtunnel.me node $HOME/trakr_circleci/test.js
       - store_artifacts:
           path: /home/circleci/trakr_result.log

workflows:
  build-tunnel-test:
    jobs:
      - build
