 version: 2.1
 jobs:
   build:
     docker:
       - image: circleci/node:lts
     environment:
       TRAKR_BASE_ENV: production
     steps:
       - checkout
       - run: sudo npm install -g localtunnel
       - run: sudo git clone https://github.com/makehero/trakr_circleci.git $HOME/trakr_circleci
       - run: cd $HOME/trakr_circleci && sudo npm install
       - run:
           name: Start tunnel
           command: sh $HOME/trakr_circleci/start_tunnel.sh
           background: true
